import type { Country } from "../types/game.types";

export const continents = [
  "Africa",
  "Asia",
  "Europe",
  "North America",
  "South America",
  "Oceania",
];

export const countries: Country[] = [
  { id: 1, name: 'Afghanistan', latitude: 33, longitude: 65, flag: '🇦🇫', continent: 'Asia' },
  { id: 2, name: 'Albania', latitude: 41, longitude: 20, flag: '🇦🇱', continent: 'Europe' },
  { id: 3, name: 'Algeria', latitude: 28, longitude: 3, flag: '🇩🇿', continent: 'Africa' },
  { id: 4, name: 'Andorra', latitude: 42.5, longitude: 1.5, flag: '🇦🇩', continent: 'Europe' },
  { id: 5, name: 'Angola', latitude: -12.5, longitude: 18.5, flag: '🇦🇴', continent: 'Africa' },
  { id: 6, name: 'Antigua and Barbuda', latitude: 17.05, longitude: -61.8, flag: '🇦🇬', continent: 'North America' },
  { id: 7, name: 'Argentina', latitude: -34, longitude: -64, flag: '🇦🇷', continent: 'South America' },
  { id: 8, name: 'Armenia', latitude: 40, longitude: 45, flag: '🇦🇲', continent: 'Asia' },
  { id: 9, name: 'Australia', latitude: -27, longitude: 133, flag: '🇦🇺', continent: 'Oceania' },
  { id: 10, name: 'Austria', latitude: 47.3333, longitude: 13.3333, flag: '🇦🇹', continent: 'Europe' },
  { id: 11, name: 'Azerbaijan', latitude: 40.5, longitude: 47.5, flag: '🇦🇿', continent: 'Asia' },
  { id: 12, name: 'Bahamas', latitude: 24.25, longitude: -76, flag: '🇧🇸', continent: 'North America' },
  { id: 13, name: 'Bahrain', latitude: 26, longitude: 50.55, flag: '🇧🇭', continent: 'Asia' },
  { id: 14, name: 'Bangladesh', latitude: 24, longitude: 90, flag: '🇧🇩', continent: 'Asia' },
  { id: 15, name: 'Barbados', latitude: 13.1667, longitude: -59.5333, flag: '🇧🇧', continent: 'North America' },
  { id: 16, name: 'Belarus', latitude: 53, longitude: 28, flag: '🇧🇾', continent: 'Europe' },
  { id: 17, name: 'Belgium', latitude: 50.8333, longitude: 4, flag: '🇧🇪', continent: 'Europe' },
  { id: 18, name: 'Belize', latitude: 17.25, longitude: -88.75, flag: '🇧🇿', continent: 'North America' },
  { id: 19, name: 'Benin', latitude: 9.5, longitude: 2.25, flag: '🇧🇯', continent: 'Africa' },
  { id: 20, name: 'Bhutan', latitude: 27.5, longitude: 90.5, flag: '🇧🇹', continent: 'Asia' },
  { id: 21, name: 'Bolivia', latitude: -17, longitude: -65, flag: '🇧🇴', continent: 'South America' },
  { id: 22, name: 'Bosnia and Herzegovina', latitude: 44, longitude: 18, flag: '🇧🇦', continent: 'Europe' },
  { id: 23, name: 'Botswana', latitude: -22, longitude: 24, flag: '🇧🇼', continent: 'Africa' },
  { id: 24, name: 'Brazil', latitude: -10, longitude: -55, flag: '🇧🇷', continent: 'South America' },
  { id: 25, name: 'Brunei', latitude: 4.5, longitude: 114.6667, flag: '🇧🇳', continent: 'Asia' },
  { id: 26, name: 'Bulgaria', latitude: 43, longitude: 25, flag: '🇧🇬', continent: 'Europe' },
  { id: 27, name: 'Burkina Faso', latitude: 13, longitude: -2, flag: '🇧🇫', continent: 'Africa' },
  { id: 28, name: 'Burundi', latitude: -3.5, longitude: 30, flag: '🇧🇮', continent: 'Africa' },
  { id: 29, name: 'Cambodia', latitude: 13, longitude: 105, flag: '🇰🇭', continent: 'Asia' },
  { id: 30, name: 'Cameroon', latitude: 6, longitude: 12, flag: '🇨🇲', continent: 'Africa' },
  { id: 31, name: 'Canada', latitude: 60, longitude: -95, flag: '🇨🇦', continent: 'North America' },
  { id: 32, name: 'Cape Verde', latitude: 16, longitude: -24, flag: '🇨🇻', continent: 'Africa' },
  { id: 33, name: 'Central African Republic', latitude: 7, longitude: 21, flag: '🇨🇫', continent: 'Africa' },
  { id: 34, name: 'Chad', latitude: 15, longitude: 19, flag: '🇹🇩', continent: 'Africa' },
  { id: 35, name: 'Chile', latitude: -30, longitude: -71, flag: '🇨🇱', continent: 'South America' },
  { id: 36, name: 'China', latitude: 35, longitude: 105, flag: '🇨🇳', continent: 'Asia' },
  { id: 37, name: 'Colombia', latitude: 4, longitude: -72, flag: '🇨🇴', continent: 'South America' },
  { id: 38, name: 'Comoros', latitude: -12.1667, longitude: 44.25, flag: '🇰🇲', continent: 'Africa' },
  { id: 39, name: 'Congo, Democratic Republic of the', latitude: 0, longitude: 25, flag: '🇨🇩', continent: 'Africa' },
  { id: 40, name: 'Congo, Republic of the', latitude: -1, longitude: 15, flag: '🇨🇬', continent: 'Africa' },
  { id: 41, name: 'Costa Rica', latitude: 10, longitude: -84, flag: '🇨🇷', continent: 'North America' },
  { id: 42, name: `Cote d'Ivoire`, latitude: 8, longitude: -5, flag: '🇨🇮', continent: 'Africa' },
  { id: 43, name: 'Croatia', latitude: 45.1667, longitude: 15.5, flag: '🇭🇷', continent: 'Europe' },
  { id: 44, name: 'Cuba', latitude: 21.5, longitude: -80, flag: '🇨🇺', continent: 'North America' },
  { id: 45, name: 'Cyprus', latitude: 35, longitude: 33, flag: '🇨🇾', continent: 'Asia' },
  { id: 46, name: 'Czech Republic', latitude: 49.75, longitude: 15.5, flag: '🇨🇿', continent: 'Europe' },
  { id: 47, name: 'Denmark', latitude: 56, longitude: 10, flag: '🇩🇰', continent: 'Europe' },
  { id: 48, name: 'Djibouti', latitude: 11.5, longitude: 43, flag: '🇩🇯', continent: 'Africa' },
  { id: 49, name: 'Dominica', latitude: 15.4167, longitude: -61.3333, flag: '🇩🇲', continent: 'North America' },
  { id: 50, name: 'Dominican Republic', latitude: 19, longitude: -70.6667, flag: '🇩🇴', continent: 'North America' },
  { id: 51, name: 'Ecuador', latitude: -2, longitude: -77.5, flag: '🇪🇨', continent: 'South America' },
  { id: 52, name: 'Egypt', latitude: 27, longitude: 30, flag: '🇪🇬', continent: 'Africa' },
  { id: 53, name: 'El Salvador', latitude: 13.8333, longitude: -88.9167, flag: '🇸🇻', continent: 'North America' },
  { id: 54, name: 'Equatorial Guinea', latitude: 2, longitude: 10, flag: '🇬🇶', continent: 'Africa' },
  { id: 55, name: 'Eritrea', latitude: 15, longitude: 39, flag: '🇪🇷', continent: 'Africa' },
  { id: 56, name: 'Estonia', latitude: 59, longitude: 26, flag: '🇪🇪', continent: 'Europe' },
  { id: 57, name: 'Eswatini', latitude: -26.5, longitude: 31.5, flag: '🇸🇿', continent: 'Africa' },
  { id: 58, name: 'Ethiopia', latitude: 8, longitude: 38, flag: '🇪🇹', continent: 'Africa' },
  { id: 59, name: 'Fiji', latitude: -18, longitude: 175, flag: '🇫🇯', continent: 'Oceania' },
  { id: 60, name: 'Finland', latitude: 64, longitude: 26, flag: '🇫🇮', continent: 'Europe' },
  { id: 61, name: 'France', latitude: 46, longitude: 2, flag: '🇫🇷', continent: 'Europe' },
  { id: 62, name: 'Gabon', latitude: -1, longitude: 11.75, flag: '🇬🇦', continent: 'Africa' },
  { id: 63, name: 'Gambia', latitude: 13.4667, longitude: -16.5667, flag: '🇬🇲', continent: 'Africa' },
  { id: 64, name: 'Georgia', latitude: 42, longitude: 43.5, flag: '🇬🇪', continent: 'Asia' },
  { id: 65, name: 'Germany', latitude: 51, longitude: 9, flag: '🇩🇪', continent: 'Europe' },
  { id: 66, name: 'Ghana', latitude: 8, longitude: -2, flag: '🇬🇭', continent: 'Africa' },
  { id: 67, name: 'Greece', latitude: 39, longitude: 22, flag: '🇬🇷', continent: 'Europe' },
  { id: 68, name: 'Grenada', latitude: 12.1167, longitude: -61.6667, flag: '🇬🇩', continent: 'North America' },
  { id: 69, name: 'Guatemala', latitude: 15.5, longitude: -90.25, flag: '🇬🇹', continent: 'North America' },
  { id: 70, name: 'Guinea', latitude: 11, longitude: -10, flag: '🇬🇳', continent: 'Africa' },
  { id: 71, name: 'Guinea-Bissau', latitude: 12, longitude: -15, flag: '🇬🇼', continent: 'Africa' },
  { id: 72, name: 'Guyana', latitude: 5, longitude: -59, flag: '🇬🇾', continent: 'South America' },
  { id: 73, name: 'Haiti', latitude: 19, longitude: -72.4167, flag: '🇭🇹', continent: 'North America' },
  { id: 74, name: 'Honduras', latitude: 15, longitude: -86.5, flag: '🇭🇳', continent: 'North America' },
  { id: 75, name: 'Hungary', latitude: 47, longitude: 20, flag: '🇭🇺', continent: 'Europe' },
  { id: 76, name: 'Iceland', latitude: 65, longitude: -18, flag: '🇮🇸', continent: 'Europe' },
  { id: 77, name: 'India', latitude: 20, longitude: 77, flag: '🇮🇳', continent: 'Asia' },
  { id: 78, name: 'Indonesia', latitude: -5, longitude: 120, flag: '🇮🇩', continent: 'Asia' },
  { id: 79, name: 'Iran', latitude: 32, longitude: 53, flag: '🇮🇷', continent: 'Asia' },
  { id: 80, name: 'Iraq', latitude: 33, longitude: 44, flag: '🇮🇶', continent: 'Asia' },
  { id: 81, name: 'Ireland', latitude: 53, longitude: -8, flag: '🇮🇪', continent: 'Europe' },
  { id: 82, name: 'Israel', latitude: 31.5, longitude: 34.75, flag: '🇮🇱', continent: 'Asia' },
  { id: 83, name: 'Italy', latitude: 42.8333, longitude: 12.8333, flag: '🇮🇹', continent: 'Europe' },
  { id: 84, name: 'Jamaica', latitude: 18.25, longitude: -77.5, flag: '🇯🇲', continent: 'North America' },
  { id: 85, name: 'Japan', latitude: 36, longitude: 138, flag: '🇯🇵', continent: 'Asia' },
  { id: 86, name: 'Jordan', latitude: 31, longitude: 36, flag: '🇯🇴', continent: 'Asia' },
  { id: 87, name: 'Kazakhstan', latitude: 48, longitude: 68, flag: '🇰🇿', continent: 'Asia' },
  { id: 88, name: 'Kenya', latitude: 1, longitude: 38, flag: '🇰🇪', continent: 'Africa' },
  { id: 89, name: 'Kiribati', latitude: 1.4167, longitude: 173, flag: '🇰🇮', continent: 'Oceania' },
  { id: 90, name: 'Kuwait', latitude: 29.5, longitude: 47.75, flag: '🇰🇼', continent: 'Asia' },
  { id: 91, name: 'Kyrgyzstan', latitude: 41, longitude: 75, flag: '🇰🇬', continent: 'Asia' },
  { id: 92, name: 'Laos', latitude: 18, longitude: 105, flag: '🇱🇦', continent: 'Asia' },
  { id: 93, name: 'Latvia', latitude: 57, longitude: 25, flag: '🇱🇻', continent: 'Europe' },
  { id: 94, name: 'Lebanon', latitude: 33.8333, longitude: 35.8333, flag: '🇱🇧', continent: 'Asia' },
  { id: 95, name: 'Lesotho', latitude: -29.5, longitude: 28.5, flag: '🇱🇸', continent: 'Africa' },
  { id: 96, name: 'Liberia', latitude: 6.5, longitude: -9.5, flag: '🇱🇷', continent: 'Africa' },
  { id: 97, name: 'Libya', latitude: 25, longitude: 17, flag: '🇱🇾', continent: 'Africa' },
  { id: 98, name: 'Liechtenstein', latitude: 47.1667, longitude: 9.5333, flag: '🇱🇮', continent: 'Europe' },
  { id: 99, name: 'Lithuania', latitude: 56, longitude: 24, flag: '🇱🇹', continent: 'Europe' },
  { id: 100, name: 'Luxembourg', latitude: 49.75, longitude: 6.1667, flag: '🇱🇺', continent: 'Europe' },
  { id: 101, name: 'Madagascar', latitude: -20, longitude: 47, flag: '🇲🇬', continent: 'Africa' },
  { id: 102, name: 'Malawi', latitude: -13.5, longitude: 34, flag: '🇲🇼', continent: 'Africa' },
  { id: 103, name: 'Malaysia', latitude: 2.5, longitude: 112.5, flag: '🇲🇾', continent: 'Asia' },
  { id: 104, name: 'Maldives', latitude: 3.25, longitude: 73, flag: '🇲🇻', continent: 'Asia' },
  { id: 105, name: 'Mali', latitude: 17, longitude: -4, flag: '🇲🇱', continent: 'Africa' },
  { id: 106, name: 'Malta', latitude: 35.8333, longitude: 14.5833, flag: '🇲🇹', continent: 'Europe' },
  { id: 107, name: 'Marshall Islands', latitude: 9, longitude: 168, flag: '🇲🇭', continent: 'Oceania' },
  { id: 108, name: 'Mauritania', latitude: 20, longitude: -12, flag: '🇲🇷', continent: 'Africa' },
  { id: 109, name: 'Mauritius', latitude: -20.2833, longitude: 57.55, flag: '🇲🇺', continent: 'Africa' },
  { id: 110, name: 'Mexico', latitude: 23, longitude: -102, flag: '🇲🇽', continent: 'North America' },
  { id: 111, name: 'Micronesia', latitude: 6.9167, longitude: 158.25, flag: '🇫🇲', continent: 'Oceania' },
  { id: 112, name: 'Moldova', latitude: 47, longitude: 29, flag: '🇲🇩', continent: 'Europe' },
  { id: 113, name: 'Monaco', latitude: 43.7333, longitude: 7.4, flag: '🇲🇨', continent: 'Europe' },
  { id: 114, name: 'Mongolia', latitude: 46, longitude: 105, flag: '🇲🇳', continent: 'Asia' },
  { id: 115, name: 'Montenegro', latitude: 42, longitude: 19, flag: '🇲🇪', continent: 'Europe' },
  { id: 116, name: 'Morocco', latitude: 32, longitude: -5, flag: '🇲🇦', continent: 'Africa' },
  { id: 117, name: 'Mozambique', latitude: -18.25, longitude: 35, flag: '🇲🇿', continent: 'Africa' },
  { id: 118, name: 'Myanmar', latitude: 22, longitude: 98, flag: '🇲🇲', continent: 'Asia' },
  { id: 119, name: 'Namibia', latitude: -22, longitude: 17, flag: '🇳🇦', continent: 'Africa' },
  { id: 120, name: 'Nauru', latitude: -0.5333, longitude: 166.9167, flag: '🇳🇷', continent: 'Oceania' },
  { id: 121, name: 'Nepal', latitude: 28, longitude: 84, flag: '🇳🇵', continent: 'Asia' },
  { id: 122, name: 'Netherlands', latitude: 52.5, longitude: 5.75, flag: '🇳🇱', continent: 'Europe' },
  { id: 123, name: 'New Zealand', latitude: -41, longitude: 174, flag: '🇳🇿', continent: 'Oceania' },
  { id: 124, name: 'Nicaragua', latitude: 13, longitude: -85, flag: '🇳🇮', continent: 'North America' },
  { id: 125, name: 'Niger', latitude: 16, longitude: 8, flag: '🇳🇪', continent: 'Africa' },
  { id: 126, name: 'Nigeria', latitude: 10, longitude: 8, flag: '🇳🇬', continent: 'Africa' },
  { id: 127, name: 'North Korea', latitude: 40, longitude: 127, flag: '🇰🇵', continent: 'Asia' },
  { id: 128, name: 'North Macedonia', latitude: 41.8333, longitude: 22, flag: '🇲🇰', continent: 'Europe' },
  { id: 129, name: 'Norway', latitude: 62, longitude: 10, flag: '🇳🇴', continent: 'Europe' },
  { id: 130, name: 'Oman', latitude: 21, longitude: 57, flag: '🇴🇲', continent: 'Asia' },
  { id: 131, name: 'Pakistan', latitude: 30, longitude: 70, flag: '🇵🇰', continent: 'Asia' },
  { id: 132, name: 'Palau', latitude: 7.5, longitude: 134.5, flag: '🇵🇼', continent: 'Oceania' },
  { id: 133, name: 'Panama', latitude: 9, longitude: -80, flag: '🇵🇦', continent: 'North America' },
  { id: 134, name: 'Papua New Guinea', latitude: -6, longitude: 147, flag: '🇵🇬', continent: 'Oceania' },
  { id: 135, name: 'Paraguay', latitude: -23, longitude: -58, flag: '🇵🇾', continent: 'South America' },
  { id: 136, name: 'Peru', latitude: -10, longitude: -76, flag: '🇵🇪', continent: 'South America' },
  { id: 137, name: 'Philippines', latitude: 13, longitude: 122, flag: '🇵🇭', continent: 'Asia' },
  { id: 138, name: 'Poland', latitude: 52, longitude: 20, flag: '🇵🇱', continent: 'Europe' },
  { id: 139, name: 'Portugal', latitude: 39.5, longitude: -8, flag: '🇵🇹', continent: 'Europe' },
  { id: 140, name: 'Qatar', latitude: 25.5, longitude: 51.25, flag: '🇶🇦', continent: 'Asia' },
  { id: 141, name: 'Romania', latitude: 46, longitude: 25, flag: '🇷🇴', continent: 'Europe' },
  { id: 142, name: 'Russia', latitude: 60, longitude: 100, flag: '🇷🇺', continent: 'Europe' },
  { id: 143, name: 'Rwanda', latitude: -2, longitude: 30, flag: '🇷🇼', continent: 'Africa' },
  { id: 144, name: 'Saint Kitts and Nevis', latitude: 17.3333, longitude: -62.75, flag: '🇰🇳', continent: 'North America' },
  { id: 145, name: 'Saint Lucia', latitude: 13.8833, longitude: -61.1333, flag: '🇱🇨', continent: 'North America' },
  { id: 146, name: 'Saint Vincent and the Grenadines', latitude: 13.25, longitude: -61.2, flag: '🇻🇨', continent: 'North America' },
  { id: 147, name: 'Samoa', latitude: -13.5833, longitude: -172.3333, flag: '🇼🇸', continent: 'Oceania' },
  { id: 148, name: 'San Marino', latitude: 43.7667, longitude: 12.4167, flag: '🇸🇲', continent: 'Europe' },
  { id: 149, name: 'Sao Tome and Principe', latitude: 1, longitude: 7, flag: '🇸🇹', continent: 'Africa' },
  { id: 150, name: 'Saudi Arabia', latitude: 25, longitude: 45, flag: '🇸🇦', continent: 'Asia' },
  { id: 151, name: 'Senegal', latitude: 14, longitude: -14, flag: '🇸🇳', continent: 'Africa' },
  { id: 152, name: 'Serbia', latitude: 44, longitude: 21, flag: '🇷🇸', continent: 'Europe' },
  { id: 153, name: 'Seychelles', latitude: -4.5833, longitude: 55.6667, flag: '🇸🇨', continent: 'Africa' },
  { id: 154, name: 'Sierra Leone', latitude: 8.5, longitude: -11.5, flag: '🇸🇱', continent: 'Africa' },
  { id: 155, name: 'Singapore', latitude: 1.3667, longitude: 103.8, flag: '🇸🇬', continent: 'Asia' },
  { id: 156, name: 'Slovakia', latitude: 48.6667, longitude: 19.5, flag: '🇸🇰', continent: 'Europe' },
  { id: 157, name: 'Slovenia', latitude: 46, longitude: 15, flag: '🇸🇮', continent: 'Europe' },
  { id: 158, name: 'Solomon Islands', latitude: -8, longitude: 159, flag: '🇸🇧', continent: 'Oceania' },
  { id: 159, name: 'Somalia', latitude: 10, longitude: 49, flag: '🇸🇴', continent: 'Africa' },
  { id: 160, name: 'South Africa', latitude: -29, longitude: 24, flag: '🇿🇦', continent: 'Africa' },
  { id: 161, name: 'South Korea', latitude: 37, longitude: 127.5, flag: '🇰🇷', continent: 'Asia' },
  { id: 162, name: 'South Sudan', latitude: 7, longitude: 30, flag: '🇸🇸', continent: 'Africa' },
  { id: 163, name: 'Spain', latitude: 40, longitude: -4, flag: '🇪🇸', continent: 'Europe' },
  { id: 164, name: 'Sri Lanka', latitude: 7, longitude: 81, flag: '🇱🇰', continent: 'Asia' },
  { id: 165, name: 'Sudan', latitude: 15, longitude: 30, flag: '🇸🇩', continent: 'Africa' },
  { id: 166, name: 'Suriname', latitude: 4, longitude: -56, flag: '🇸🇷', continent: 'South America' },
  { id: 167, name: 'Sweden', latitude: 62, longitude: 15, flag: '🇸🇪', continent: 'Europe' },
  { id: 168, name: 'Switzerland', latitude: 47, longitude: 8, flag: '🇨🇭', continent: 'Europe' },
  { id: 169, name: 'Syria', latitude: 35, longitude: 38, flag: '🇸🇾', continent: 'Asia' },
  { id: 170, name: 'Taiwan', latitude: 23.5, longitude: 121, flag: '🇹🇼', continent: 'Asia' },
  { id: 171, name: 'Tajikistan', latitude: 39, longitude: 71, flag: '🇹🇯', continent: 'Asia' },
  { id: 172, name: 'Tanzania', latitude: -6, longitude: 35, flag: '🇹🇿', continent: 'Africa' },
  { id: 173, name: 'Thailand', latitude: 15, longitude: 100, flag: '🇹🇭', continent: 'Asia' },
  { id: 174, name: 'Timor-Leste', latitude: -8.8333, longitude: 125.9167, flag: '🇹🇱', continent: 'Asia' },
  { id: 175, name: 'Togo', latitude: 8, longitude: 1.1667, flag: '🇹🇬', continent: 'Africa' },
  { id: 176, name: 'Tonga', latitude: -20, longitude: -175, flag: '🇹🇴', continent: 'Oceania' },
  { id: 177, name: 'Trinidad and Tobago', latitude: 11, longitude: -61, flag: '🇹🇹', continent: 'North America' },
  { id: 178, name: 'Tunisia', latitude: 34, longitude: 9, flag: '🇹🇳', continent: 'Africa' },
  { id: 179, name: 'Turkey', latitude: 39, longitude: 35, flag: '🇹🇷', continent: 'Asia' },
  { id: 180, name: 'Turkmenistan', latitude: 40, longitude: 60, flag: '🇹🇲', continent: 'Asia' },
  { id: 181, name: 'Tuvalu', latitude: -8, longitude: 178, flag: '🇹🇻', continent: 'Oceania' },
  { id: 182, name: 'Uganda', latitude: 1, longitude: 32, flag: '🇺🇬', continent: 'Africa' },
  { id: 183, name: 'Ukraine', latitude: 49, longitude: 32, flag: '🇺🇦', continent: 'Europe' },
  { id: 184, name: 'United Arab Emirates', latitude: 24, longitude: 54, flag: '🇦🇪', continent: 'Asia' },
  { id: 185, name: 'United Kingdom', latitude: 54, longitude: -2, flag: '🇬🇧', continent: 'Europe' },
  { id: 186, name: 'United States', latitude: 38, longitude: -97, flag: '🇺🇸', continent: 'North America' },
  { id: 187, name: 'Uruguay', latitude: -33, longitude: -56, flag: '🇺🇾', continent: 'South America' },
  { id: 188, name: 'Uzbekistan', latitude: 41, longitude: 64, flag: '🇺🇿', continent: 'Asia' },
  { id: 189, name: 'Vanuatu', latitude: -16, longitude: 167, flag: '🇻🇺', continent: 'Oceania' },
  { id: 190, name: 'Vatican City', latitude: 41.9, longitude: 12.45, flag: '🇻🇦', continent: 'Europe' },
  { id: 191, name: 'Venezuela', latitude: 8, longitude: -66, flag: '🇻🇪', continent: 'South America' },
  { id: 192, name: 'Vietnam', latitude: 16, longitude: 106, flag: '🇻🇳', continent: 'Asia' },
  { id: 193, name: 'Yemen', latitude: 15, longitude: 48, flag: '🇾🇪', continent: 'Asia' },
  { id: 194, name: 'Zambia', latitude: -15, longitude: 30, flag: '🇿🇲', continent: 'Africa' },
  { id: 195, name: 'Zimbabwe', latitude: -20, longitude: 30, flag: '🇿🇼', continent: 'Africa' },
];